[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_world = "FG2t6RZk7GPPxqQ58sKS6JKT7rybauhFkvjnff8e2KMS"
token_metadata="45jQhQUcCYWxa7LCosvoyxB6Qmwntf26Q14YVKCqSYRo"
token_metadata_program="45jQhQUcCYWxa7LCosvoyxB6Qmwntf26Q14YVKCqSYRo"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "Localnet"
# cluster = "Devnet"
cluster = "http://127.0.0.1:8899"
wallet = "~/.config/solana/id.json"

[token_metadata]
address="45jQhQUcCYWxa7LCosvoyxB6Qmwntf26Q14YVKCqSYRo"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/cpi_hand_lever.ts"
