[toolchain]
anchor_version = "0.30.1"
solana_version = "2.0.3"

[package]
name = "transfer_hook"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "transfer_hook"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = { version = "0.30.1", features = ["interface-instructions"] }
anchor-spl = "0.30.1"
solana-program = "=1.18.21"
spl-tlv-account-resolution = "0.6.0"
spl-transfer-hook-interface = "0.6.0"
